# Generated by Django 3.0.9 on 2020-08-04 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'managed': False},
        ),
    ]
