# Generated by Django 3.0.9 on 2020-08-04 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0002_auto_20200804_0713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
