# Generated by Django 3.0.9 on 2020-08-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_bot', '0003_delete_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=255)),
                ('type_name', models.CharField(max_length=255)),
                ('timestamp', models.FloatField(blank=True, null=True)),
                ('intent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('action_name', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
    ]
