# Generated by Django 3.1 on 2020-08-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_bot', '0006_textuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'intent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nlu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'nlu',
                'managed': False,
            },
        ),
    ]
